// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvhdeML7CyiKzZr55hBgsOhhxjdGlP7og',
    appId: '1:373309470048:web:2f2cb3653dfda0269f5a05',
    messagingSenderId: '373309470048',
    projectId: 'pertemuan8-f13cd',
    authDomain: 'pertemuan8-f13cd.firebaseapp.com',
    storageBucket: 'pertemuan8-f13cd.appspot.com',
    measurementId: 'G-W5LNGVJVMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGmNnT0iLv1uNUKtwnb6wPO3xw0rVXfMY',
    appId: '1:373309470048:android:42bd956a464b6e419f5a05',
    messagingSenderId: '373309470048',
    projectId: 'pertemuan8-f13cd',
    storageBucket: 'pertemuan8-f13cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc4KKVD7sG2NBMiG92ZXrbA8MXY1In_7c',
    appId: '1:373309470048:ios:f67935a91e1669be9f5a05',
    messagingSenderId: '373309470048',
    projectId: 'pertemuan8-f13cd',
    storageBucket: 'pertemuan8-f13cd.appspot.com',
    iosBundleId: 'com.example.thismyapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc4KKVD7sG2NBMiG92ZXrbA8MXY1In_7c',
    appId: '1:373309470048:ios:f67935a91e1669be9f5a05',
    messagingSenderId: '373309470048',
    projectId: 'pertemuan8-f13cd',
    storageBucket: 'pertemuan8-f13cd.appspot.com',
    iosBundleId: 'com.example.thismyapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvhdeML7CyiKzZr55hBgsOhhxjdGlP7og',
    appId: '1:373309470048:web:8f6488674b3cadad9f5a05',
    messagingSenderId: '373309470048',
    projectId: 'pertemuan8-f13cd',
    authDomain: 'pertemuan8-f13cd.firebaseapp.com',
    storageBucket: 'pertemuan8-f13cd.appspot.com',
    measurementId: 'G-L79SBHY7NH',
  );

}